export default actionTypes = {
    SIGNUP_PROGRESS:"SIGNUP_PROGRESS",
    SIGNUP_SUCCEED:"SIGNUP_SUCCEED",
    SIGNUP_ERROR:"SIGNUP_ERROR",
    SIGNUP_ERROR_ALERT:"SIGNUP_ERROR_ALERT",
    SIGNIN_PROGRESS:"SIGNIN_PROGRESS",
    SIGNIN_SUCCEED:"SIGNIN_SUCCEED",
    SIGNIN_ERROR:"SIGNIN_ERROR",
    SIGNIN_ERROR_ALERT:"SIGNIN_ERROR_ALERT"
}